2017-11-25 12:56:12,966:Sat Nov 25 12:56:12 2017
2017-11-25 12:56:12,966:Server Starts - 192.168.1.4:8080
2017-11-25 12:56:39,425:Sat Nov 25 12:56:39 2017
2017-11-25 12:56:39,426:Server Stops - 192.168.1.4:8080
2017-11-25 20:11:34,603:Sat Nov 25 20:11:34 2017
2017-11-25 20:11:34,603:Created pastebin data directory:
2017-11-25 20:11:34,603:data
2017-11-25 20:11:34,604:Sat Nov 25 20:11:34 2017
2017-11-25 20:11:34,604:Server Starts - None:None
2017-11-25 20:11:34,604:Traceback (most recent call last):
2017-11-25 20:11:34,604:  File "./pypastebin.py", line 423, in <module>
2017-11-25 20:11:34,604:httpd = BaseHTTPServer.HTTPServer((HTTP_IP, HTTP_PORT), MyHandler)
2017-11-25 20:11:34,604:  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
2017-11-25 20:11:34,604:self.server_bind()
2017-11-25 20:11:34,604:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
2017-11-25 20:11:34,604:SocketServer.TCPServer.server_bind(self)
2017-11-25 20:11:34,604:  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
2017-11-25 20:11:34,604:self.socket.bind(self.server_address)
2017-11-25 20:11:34,604:  File "/usr/lib/python2.7/socket.py", line 228, in meth
2017-11-25 20:11:34,605:return getattr(self._sock,name)(*args)
2017-11-25 20:11:34,605:TypeError
2017-11-25 20:11:34,605::
2017-11-25 20:11:34,605:coercing to Unicode: need string or buffer, NoneType found
2017-11-25 20:11:45,105:Sat Nov 25 20:11:45 2017
2017-11-25 20:11:45,105:Server Starts - 192.168.1.4:80
2017-11-25 20:11:45,105:Traceback (most recent call last):
2017-11-25 20:11:45,105:  File "./pypastebin.py", line 423, in <module>
2017-11-25 20:11:45,106:httpd = BaseHTTPServer.HTTPServer((HTTP_IP, HTTP_PORT), MyHandler)
2017-11-25 20:11:45,106:  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
2017-11-25 20:11:45,106:self.server_bind()
2017-11-25 20:11:45,106:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
2017-11-25 20:11:45,106:SocketServer.TCPServer.server_bind(self)
2017-11-25 20:11:45,106:  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
2017-11-25 20:11:45,106:self.socket.bind(self.server_address)
2017-11-25 20:11:45,106:  File "/usr/lib/python2.7/socket.py", line 228, in meth
2017-11-25 20:11:45,106:return getattr(self._sock,name)(*args)
2017-11-25 20:11:45,106:socket
2017-11-25 20:11:45,106:.
2017-11-25 20:11:45,106:error
2017-11-25 20:11:45,106::
2017-11-25 20:11:45,106:[Errno 13] Permission denied
2017-11-25 20:11:55,276:Sat Nov 25 20:11:55 2017
2017-11-25 20:11:55,276:Server Starts - 192.168.1.4:8080
2017-11-25 20:12:06,300:192.168.1.4 - - [25/Nov/2017 20:12:06] "GET / HTTP/1.1" - -
2017-11-25 20:12:06,301:192.168.1.4 - - [25/Nov/2017 20:12:06] "GET / HTTP/1.1" 200 -
2017-11-25 20:12:06,377:192.168.1.4 - - [25/Nov/2017 20:12:06] "GET /style.css HTTP/1.1" - -
2017-11-25 20:12:06,377:192.168.1.4 - - [25/Nov/2017 20:12:06] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:12:06,657:192.168.1.4 - - [25/Nov/2017 20:12:06] "GET /favicon.ico HTTP/1.1" 200 -
2017-11-25 20:12:12,215:192.168.1.4 - - [25/Nov/2017 20:12:12] "GET /pastebinit HTTP/1.1" - -
2017-11-25 20:12:12,215:192.168.1.4 - - [25/Nov/2017 20:12:12] "GET /pastebinit HTTP/1.1" 200 -
2017-11-25 20:12:12,338:192.168.1.4 - - [25/Nov/2017 20:12:12] "GET /style.css HTTP/1.1" - -
2017-11-25 20:12:12,339:192.168.1.4 - - [25/Nov/2017 20:12:12] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:12:19,619:Sat Nov 25 20:12:19 2017
2017-11-25 20:12:19,619:Server Stops - 192.168.1.4:8080
2017-11-25 20:33:35,296:Sat Nov 25 20:33:35 2017
2017-11-25 20:33:35,296:Server Starts - 192.168.1.4:8080
2017-11-25 20:33:38,931:192.168.1.4 - - [25/Nov/2017 20:33:38] "GET /pastebinit HTTP/1.1" - -
2017-11-25 20:33:38,931:192.168.1.4 - - [25/Nov/2017 20:33:38] "GET /pastebinit HTTP/1.1" 200 -
2017-11-25 20:33:38,986:192.168.1.4 - - [25/Nov/2017 20:33:38] "GET /style.css HTTP/1.1" - -
2017-11-25 20:33:38,986:192.168.1.4 - - [25/Nov/2017 20:33:38] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:33:38,986:----------------------------------------
2017-11-25 20:33:38,987:Exception happened during processing of request from
2017-11-25 20:33:38,987:('192.168.1.4', 34390)
2017-11-25 20:33:38,987:Traceback (most recent call last):
2017-11-25 20:33:38,987:  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-11-25 20:33:38,987:    self.process_request(request, client_address)
2017-11-25 20:33:38,987:  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-11-25 20:33:38,987:    self.finish_request(request, client_address)
2017-11-25 20:33:38,988:  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-11-25 20:33:38,988:    self.RequestHandlerClass(request, client_address, self)
2017-11-25 20:33:38,988:  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-11-25 20:33:38,988:    self.handle()
2017-11-25 20:33:38,988:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-11-25 20:33:38,988:    self.handle_one_request()
2017-11-25 20:33:38,988:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-11-25 20:33:38,988:    method()
2017-11-25 20:33:38,989:  File "./pypastebin.py", line 339, in do_GET
2017-11-25 20:33:38,989:    self.wfile.write(STYLE_CSS % {"CONTEXT_PATH": self.get_context_path()})
2017-11-25 20:33:38,989:NameError: global name 'STYLE_CSS' is not defined
2017-11-25 20:33:38,989:----------------------------------------
2017-11-25 20:33:41,090:192.168.1.4 - - [25/Nov/2017 20:33:41] "GET / HTTP/1.1" - -
2017-11-25 20:33:41,090:192.168.1.4 - - [25/Nov/2017 20:33:41] "GET / HTTP/1.1" 200 -
2017-11-25 20:33:41,121:192.168.1.4 - - [25/Nov/2017 20:33:41] "GET /style.css HTTP/1.1" - -
2017-11-25 20:33:41,122:192.168.1.4 - - [25/Nov/2017 20:33:41] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:33:41,122:----------------------------------------
2017-11-25 20:33:41,122:Exception happened during processing of request from
2017-11-25 20:33:41,122:('192.168.1.4', 34394)
2017-11-25 20:33:41,122:Traceback (most recent call last):
2017-11-25 20:33:41,122:  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-11-25 20:33:41,122:    self.process_request(request, client_address)
2017-11-25 20:33:41,122:  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-11-25 20:33:41,123:    self.finish_request(request, client_address)
2017-11-25 20:33:41,123:  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-11-25 20:33:41,123:    self.RequestHandlerClass(request, client_address, self)
2017-11-25 20:33:41,123:  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-11-25 20:33:41,123:    self.handle()
2017-11-25 20:33:41,123:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-11-25 20:33:41,123:    self.handle_one_request()
2017-11-25 20:33:41,123:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-11-25 20:33:41,123:    method()
2017-11-25 20:33:41,123:  File "./pypastebin.py", line 339, in do_GET
2017-11-25 20:33:41,124:    self.wfile.write(STYLE_CSS % {"CONTEXT_PATH": self.get_context_path()})
2017-11-25 20:33:41,124:NameError: global name 'STYLE_CSS' is not defined
2017-11-25 20:33:41,124:----------------------------------------
2017-11-25 20:33:44,426:Sat Nov 25 20:33:44 2017
2017-11-25 20:33:44,426:Server Stops - 192.168.1.4:8080
2017-11-25 20:34:26,025:Sat Nov 25 20:34:26 2017
2017-11-25 20:34:26,025:Server Starts - 192.168.1.4:8080
2017-11-25 20:34:28,401:192.168.1.4 - - [25/Nov/2017 20:34:28] "GET / HTTP/1.1" - -
2017-11-25 20:34:28,401:192.168.1.4 - - [25/Nov/2017 20:34:28] "GET / HTTP/1.1" 200 -
2017-11-25 20:34:28,422:192.168.1.4 - - [25/Nov/2017 20:34:28] "GET /style.css HTTP/1.1" - -
2017-11-25 20:34:28,422:192.168.1.4 - - [25/Nov/2017 20:34:28] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:34:28,422:----------------------------------------
2017-11-25 20:34:28,422:Exception happened during processing of request from
2017-11-25 20:34:28,422:('192.168.1.4', 34444)
2017-11-25 20:34:28,423:Traceback (most recent call last):
2017-11-25 20:34:28,423:  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-11-25 20:34:28,423:    self.process_request(request, client_address)
2017-11-25 20:34:28,423:  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-11-25 20:34:28,423:    self.finish_request(request, client_address)
2017-11-25 20:34:28,423:  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-11-25 20:34:28,423:    self.RequestHandlerClass(request, client_address, self)
2017-11-25 20:34:28,423:  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-11-25 20:34:28,423:    self.handle()
2017-11-25 20:34:28,424:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-11-25 20:34:28,424:    self.handle_one_request()
2017-11-25 20:34:28,424:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-11-25 20:34:28,424:    method()
2017-11-25 20:34:28,424:  File "./pypastebin.py", line 356, in do_GET
2017-11-25 20:34:28,424:    self.wfile.write(STYLE_CSS % {"CONTEXT_PATH": self.get_context_path()})
2017-11-25 20:34:28,424:ValueError: unsupported format character ';' (0x3b) at index 639
2017-11-25 20:34:28,424:----------------------------------------
2017-11-25 20:34:30,454:192.168.1.4 - - [25/Nov/2017 20:34:30] "GET / HTTP/1.1" - -
2017-11-25 20:34:30,454:192.168.1.4 - - [25/Nov/2017 20:34:30] "GET / HTTP/1.1" 200 -
2017-11-25 20:34:30,489:192.168.1.4 - - [25/Nov/2017 20:34:30] "GET /style.css HTTP/1.1" - -
2017-11-25 20:34:30,489:192.168.1.4 - - [25/Nov/2017 20:34:30] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:34:30,489:----------------------------------------
2017-11-25 20:34:30,489:Exception happened during processing of request from
2017-11-25 20:34:30,490:('192.168.1.4', 34454)
2017-11-25 20:34:30,490:Traceback (most recent call last):
2017-11-25 20:34:30,490:  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-11-25 20:34:30,490:    self.process_request(request, client_address)
2017-11-25 20:34:30,490:  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-11-25 20:34:30,490:    self.finish_request(request, client_address)
2017-11-25 20:34:30,490:  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-11-25 20:34:30,490:    self.RequestHandlerClass(request, client_address, self)
2017-11-25 20:34:30,491:  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-11-25 20:34:30,491:    self.handle()
2017-11-25 20:34:30,491:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-11-25 20:34:30,491:    self.handle_one_request()
2017-11-25 20:34:30,491:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-11-25 20:34:30,491:    method()
2017-11-25 20:34:30,491:  File "./pypastebin.py", line 356, in do_GET
2017-11-25 20:34:30,491:    self.wfile.write(STYLE_CSS % {"CONTEXT_PATH": self.get_context_path()})
2017-11-25 20:34:30,492:ValueError: unsupported format character ';' (0x3b) at index 639
2017-11-25 20:34:30,492:----------------------------------------
2017-11-25 20:34:32,765:Sat Nov 25 20:34:32 2017
2017-11-25 20:34:32,765:Server Stops - 192.168.1.4:8080
2017-11-25 20:35:03,697:Sat Nov 25 20:35:03 2017
2017-11-25 20:35:03,697:Server Starts - 192.168.1.4:8080
2017-11-25 20:35:03,911:Sat Nov 25 20:35:03 2017
2017-11-25 20:35:03,911:Server Stops - 192.168.1.4:8080
2017-11-25 20:35:27,976:Sat Nov 25 20:35:27 2017
2017-11-25 20:35:27,976:Server Starts - 192.168.1.4:8080
2017-11-25 20:35:30,014:192.168.1.4 - - [25/Nov/2017 20:35:30] "GET / HTTP/1.1" - -
2017-11-25 20:35:30,015:192.168.1.4 - - [25/Nov/2017 20:35:30] "GET / HTTP/1.1" 200 -
2017-11-25 20:35:30,044:192.168.1.4 - - [25/Nov/2017 20:35:30] "GET /style.css HTTP/1.1" - -
2017-11-25 20:35:30,044:192.168.1.4 - - [25/Nov/2017 20:35:30] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:35:30,044:----------------------------------------
2017-11-25 20:35:30,044:Exception happened during processing of request from
2017-11-25 20:35:30,045:('192.168.1.4', 34478)
2017-11-25 20:35:30,045:Traceback (most recent call last):
2017-11-25 20:35:30,045:  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
2017-11-25 20:35:30,045:    self.process_request(request, client_address)
2017-11-25 20:35:30,045:  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
2017-11-25 20:35:30,045:    self.finish_request(request, client_address)
2017-11-25 20:35:30,045:  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2017-11-25 20:35:30,046:    self.RequestHandlerClass(request, client_address, self)
2017-11-25 20:35:30,046:  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2017-11-25 20:35:30,046:    self.handle()
2017-11-25 20:35:30,046:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2017-11-25 20:35:30,046:    self.handle_one_request()
2017-11-25 20:35:30,046:  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2017-11-25 20:35:30,046:    method()
2017-11-25 20:35:30,046:  File "./pypastebin.py", line 356, in do_GET
2017-11-25 20:35:30,047:    self.wfile.write(STYLE_CSS % {"CONTEXT_PATH": self.get_context_path()})
2017-11-25 20:35:30,047:ValueError: unsupported format character ';' (0x3b) at index 639
2017-11-25 20:35:30,047:----------------------------------------
2017-11-25 20:35:32,761:Sat Nov 25 20:35:32 2017
2017-11-25 20:35:32,762:Server Stops - 192.168.1.4:8080
2017-11-25 20:36:07,957:Sat Nov 25 20:36:07 2017
2017-11-25 20:36:07,957:Server Starts - 192.168.1.4:8080
2017-11-25 20:36:09,511:192.168.1.4 - - [25/Nov/2017 20:36:09] "GET / HTTP/1.1" - -
2017-11-25 20:36:09,511:192.168.1.4 - - [25/Nov/2017 20:36:09] "GET / HTTP/1.1" 200 -
2017-11-25 20:36:09,548:192.168.1.4 - - [25/Nov/2017 20:36:09] "GET /style.css HTTP/1.1" - -
2017-11-25 20:36:09,548:192.168.1.4 - - [25/Nov/2017 20:36:09] "GET /style.css HTTP/1.1" 200 -
2017-11-25 20:36:11,606:Sat Nov 25 20:36:11 2017
2017-11-25 20:36:11,606:Server Stops - 192.168.1.4:8080
